version: '2'
services:
    avayabloomadmin-app:
        image: avayabloomadmin
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://avayabloomadmin-postgresql:5432/AvayaBloomAdmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avayabloomadmin-postgresql:
        extends:
            file: postgresql.yml
            service: avayabloomadmin-postgresql
